version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "ping"
      - run: git clone https://github.com/NickLavrov/circle-pong.git
      - run: cd circle-pong && echo "$((`cat count.txt` + 1))" > count.txt
      - run: cd circle-pong && git status
