version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "ping"
      - run: git clone https://github.com/NickLavrov/circle-ping.git
      - run: cd circle-ping && echo "$((`cat count.txt` + 1))" > count.txt
      - run: cd circle-ping && git config user.email "nlavrov999@gmail.com"
      - run: cd circle-ping && git config --global user.name "NickLavrov"
      - run: cd circle-ping && git commit -am 'Increase count.'
      - run: git push -q https://${GITHUB_TOKEN}@github.com/NickLavrov/circle-ping.git HEAD
